### ISSUE TITLE
The Faroe Island has a wrong timezone

### ISSUE THREAD

**Issue by jidesoft** [drtimcooper/LatLongToTimezone#32]
I can try to fix it myself if you guys can show me the steps. I saw Faroe has a separate shape in the shp file, but it maps to a wrong timezone name.

**Comment by 2ndCharter** [comment]
Hey Tim,

Can you unsubscribe me from this please? I no longer have access to GitHub and have since retired.

Best regards,

Steve

Stephen C. Andrews

This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed. If you have received this email in error please notify the system manager. This message contains confidential information and is intended only for the individual named. If you are not the named addressee you should not disseminate, distribute or copy this e-mail. Please notify the sender immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. If you are not the intended recipient you are notified that disclosing, copying, distributing or taking any action in reliance on the contents of this information is strictly prohibited.

**Comment by drtimcooper** [comment]
I don't think the problem is resolved but there's no-one around who cares enough to fix it.

**Comment by jidesoft** [comment]
:-( I care, and the Faroeses and people who travel to the Faroe Islands care. You should care too as it indicates some fundamental issues in the generated code. From what I can see the shapefile is correct yet the timezone is still wrong.

**Comment by drtimcooper** [comment]
Okay, apologies for my rude comment.  I didn't realise this was a fairly recently created issue.  Actually I have never been to the Faroes but have read the Faroese saga twice (Thrand, Sigurd, Sigmund et al).

Anyway, if this is a data bug then it'll be easy to fix, but if it's an algorithm bug then it'll be very difficult to fix.  From your Aug 21 comment it sounds like a data bug.  Would you be willing to attempt a fix?  There is no automated process for updating the .shp file.  You could hunt around for the most recent authoritative version of it, (and hopefully Crimea is in the Russian timezone there), check that the Faroes are correct in that version, chase it up with the producers if not, and/or do a manual fixup, and regenerate the various target files.

**Comment by jidesoft** [comment]
Thank you. My debug shows it returns a wrong timezone index at one of the if statement. How do you associate the .shp file with the timezone? Can you check the .shp has a separate region for Faroe Island?I loaded it into Google Earth and saw it is, but I am not sure how you associate the .shp with the timezone.

**Comment by drtimcooper** [comment]
Hi Jidesoft:

               One approach would be to hack your .java source file at the point where you can see it returns the wrong value.  I think you need to return 362 or something for “Atlantic/Faroe”.

               The next step would be to hack the “timezone.json” file – find the relevant polygon and modify the associated timezone string.

               Going another step back up the pipeline, confirm that the currently committed version of the .shp file (which is processed into “timezone.json”) has the wrong data and find out who made it and get them to fix it, and then do all the processing again.

**Comment by jidesoft** [comment]
Thanks for the info. After I debug, I found the problem is at 

 

else if (lat < 66.536849f)
 return 211;
else
 return 299;

 

299 is Faroe timezone string. Faroe Islands is below 63N. I changed < to >=, it works. 

 

else if (lat >= 66.536849f)
    return 211;
else
    return 299;

 

But I am not sure how it goes back to timezone.json. 

 

Thanks,

-David

**Comment by drtimcooper** [comment]
I don’t know if this change will break something else for you…I don’t know what timezone lies above the Faroes….probably nothing much.

 

Anyway, if you’re happy with this change then my advice is to make it locally, and keep it, and never upgrade.  The timezone polygons are extremely stable…moreso than the timezone offsets.  And my tool only maps lat/longs to timezone identifiers, so your local libraries (I forget which platform you’re using) will take care of mapping (timezone identifier, time) --> GMT offset.
